"""
1_2_2: Multimodal (Gemini) - Multimodal Support

What you'll learn in this script:
================================
1. Image Understanding (Gemini Vision)
2. Audio Understanding (Gemini Audio)
3. Video Understanding (Gemini Video)
4. PDF Understanding (Gemini)

Gemini API Support:
==================
| Media | Support | Notes |
|-------|---------|-------|
| Image Generation | Limited | Imagen (limited access) |
| Image Understanding | Yes | Gemini Vision |
| Speech Generation | No | Not supported |
| Speech Understanding | Yes | Gemini Audio |
| Video Understanding | Yes | Gemini Video |
| PDF Understanding | Yes | Direct upload |

Prerequisites:
--------
export GOOGLE_API_KEY=your-api-key
"""

import os
import time
from pathlib import Path
from typing import Annotated
from dotenv import load_dotenv
import weave
from weave import Content
from PIL import Image, ImageDraw
import google.generativeai as genai
from config_loader import get_model_name

# Load environment variables
load_dotenv()

# Initialize Weave
weave.init(f"{os.getenv('WANDB_ENTITY')}/{os.getenv('WANDB_PROJECT', 'weave-handson')}")

# Configure Gemini
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Output directory
OUTPUT_DIR = Path(__file__).parent.parent / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)


# =============================================================================
# 1. Image Understanding (Gemini Vision)
# =============================================================================
print("\n" + "=" * 60)
print("1. Image Understanding (Gemini Vision)")
print("=" * 60)


@weave.op()
def analyze_image(image_path: Annotated[str, Content]) -> str:
    """Analyze image with Gemini
    
    Gemini supports image understanding with Vision.
    """
    model = genai.GenerativeModel(get_model_name())
    img = Image.open(image_path)
    response = model.generate_content(["Describe this image briefly.", img])
    return response.text


# Create sample image
sample_img = Image.new('RGB', (200, 100), color='lightgreen')
draw = ImageDraw.Draw(sample_img)
draw.text((50, 40), "Hello Gemini!", fill='darkgreen')
sample_path = OUTPUT_DIR / "sample_image_gemini.png"
sample_img.save(sample_path)

description = analyze_image(str(sample_path))
print(f"Image analysis: {description[:80]}...")


# =============================================================================
# 2. Audio Understanding (Gemini Audio)
# =============================================================================
print("\n" + "=" * 60)
print("2. Audio Understanding (Gemini Audio)")
print("=" * 60)


@weave.op()
def analyze_audio(audio_path: Annotated[str, Content]) -> str:
    """Analyze audio with Gemini
    
    Gemini can upload and understand audio files.
    Note: Speech generation (TTS) is not supported.
    """
    audio_file = genai.upload_file(audio_path)
    model = genai.GenerativeModel(get_model_name())
    response = model.generate_content([audio_file, "Transcribe this audio."])
    return response.text


# Use audio file generated by OpenAI TTS
audio_path = OUTPUT_DIR / "tts_output.mp3"
if audio_path.exists():
    transcription = analyze_audio(str(audio_path))
    print(f"Audio analysis: {transcription[:80]}...")
else:
    print("Audio file not found. Run 1_2_2_multimodal_openai.py first.")


# =============================================================================
# 3. Video Generation and Upload (Gemini Video)
# =============================================================================
print("\n" + "=" * 60)
print("3. Video Generation and Upload (Gemini Video)")
print("=" * 60)


@weave.op()
def generate_video() -> Annotated[str, Content]:
    """Generate video using imageio
    
    Returns the video file path and saves it to Weave.
    """
    import numpy as np
    import imageio.v3 as iio
    
    video_path = OUTPUT_DIR / "sample_video.mp4"
    
    # Create animation frames (60 frames, 30fps = 2 seconds)
    frames = []
    for i in range(60):
        # Create image with PIL
        img = Image.new('RGB', (640, 480), color=(100, 149, 237))
        draw = ImageDraw.Draw(img)
        
        # Moving text
        x = 100 + i * 5
        draw.rectangle([x, 200, x + 200, 280], fill=(255, 255, 255))
        draw.text((x + 20, 220), f"Frame {i+1}", fill=(0, 0, 0))
        
        # Convert to numpy array
        frames.append(np.array(img))
    
    # Save video with imageio
    iio.imwrite(str(video_path), frames, fps=30, codec='libx264')
    print(f"Video file created: {video_path}")
    
    return str(video_path)


@weave.op()
def analyze_video(video_path: Annotated[str, Content]) -> str:
    """Analyze video with Gemini
    
    Gemini supports video file upload and analysis.
    OpenAI does not support video.
    """
    # Upload video
    video_file = genai.upload_file(video_path)
    
    # Wait for processing
    while video_file.state.name == "PROCESSING":
        time.sleep(2)
        video_file = genai.get_file(video_file.name)
    
    # Analyze
    model = genai.GenerativeModel(get_model_name())
    response = model.generate_content([video_file, "Describe this video briefly."])
    return response.text


# Generate video
video_path = generate_video()

# Analyze video
video_description = analyze_video(video_path)
print(f"Video analysis: {video_description[:80]}...")


# =============================================================================
# 4. PDF Understanding (Gemini)
# =============================================================================
print("\n" + "=" * 60)
print("4. PDF Understanding (Gemini)")
print("=" * 60)

# Create sample PDF
try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    
    pdf_path = OUTPUT_DIR / "sample_document_gemini.pdf"
    c = canvas.Canvas(str(pdf_path), pagesize=letter)
    c.drawString(100, 750, "Gemini Multimodal Demo")
    c.drawString(100, 720, "This is a sample PDF document.")
    c.drawString(100, 690, "Gemini can directly upload and analyze PDF files.")
    c.save()
    print(f"PDF file created: {pdf_path}")
except ImportError:
    print("reportlab is not installed")
    pdf_path = None


@weave.op()
def analyze_pdf(pdf_path: Annotated[str, Content]) -> str:
    """Analyze PDF with Gemini
    
    Gemini can directly upload and analyze PDF files.
    No image conversion needed, simpler than OpenAI.
    """
    pdf_file = genai.upload_file(pdf_path)
    model = genai.GenerativeModel(get_model_name())
    response = model.generate_content([pdf_file, "Summarize this PDF content."])
    return response.text


if pdf_path:
    summary = analyze_pdf(str(pdf_path))
    print(f"PDF analysis: {summary[:80]}...")
